package com.stubhub.qe.platform.elephant.agency.workshop

/**
 *
 * @author Hongfei Zhou
 * @version 1.0, Aug. 13 2014
 */
object DriverParameters {
    final val TEST_CONFIG: String = "testConfig"
    final val POOL: String = "pool"
    final val POOL_TYPE: String = "poolType"
    final val SITE: String = "site"
    final val LOCALIZED_BUILD: String = "localizedBuild"
    final val COBRAND: String = "cobrand"
    final val POP3_HOST: String = "pop3Host"
    final val GBH_SITE: String = "gbhSite"
    final val IS_MOBILE_SITE: String = "isMobileSite"
    final val DCT_WS_END_POINT_URL: String = "dctEndPointURL"
    final val WEB_SESSION_TIME_OUT: String = "webSessionTimeOut"
    final val IMPLICIT_WAIT_TIME_OUT: String = "implicitWaitTimeOut"
    final val EXPLICIT_WAIT_TIME_OUT: String = "explicitWaitTimeOut"
    final val PAGE_LOAD_TIME_OUT: String = "pageLoadTimeout"
    final val WEB_DRIVER_GRID: String = "webDriverGrid"
    final val WEB_RUN_MODE: String = "webRunMode"
    final val WEB_RUN_BROWSER: String = "browser"
    final val WEB_RUN_BROWSER_VERSION: String = "browserVersion"
    final val WEB_RUN_PLATFORM: String = "platform"
    final val FIREFOX_USER_PROFILE_PATH: String = "firefoxUserProfilePath"
    final val USE_FIREFOX_DEFAULT_PROFILE: String = "useFirefoxDefaultProfile"
    final val OPERA_USER_PROFILE_PATH: String = "operaUserProfilePath"
    final val FIREFOX_BINARY_PATH: String = "firefoxBinaryPath"
    final val CHROME_DRIVER_PATH: String = "chromeDriverPath"
    final val CHROME_BINARY_PATH: String = "chromeBinaryPath"
    final val IE_DRIVER_PATH: String = "ieDriverPath"
    final val USER_AGENT: String = "userAgent"
    final val APP_NAME: String = "appName"
    final val APP_VERSION: String = "appVersion"
    final val ANDROID_TARGET: String = "androidTarget"
    final val SET_ASSUME_UNTRUSTED_CERTIFICATE_ISSUERS: String = "setAssumeUntrustedCertificateIssuer"
    final val SET_ACCEPT_UNTRUSTED_CERTIFICATES: String = "setAcceptUntrustedCertificates"
    final val ENABLE_JAVASCRIPT: String = "enableJavascript"
    final val NTLM_AUTH_TRUSTED_URIS: String = "ntlmAuthTrustedUris"
    final val BROWSER_DOWNLOAD_DIR: String = "browserDownloadDir"
    final val BROWSER_WINDOW_SIZE: String = "browserWindowSize"
    final val ADD_JSERROR_COLLECTOR_EXTENSION: String = "addJSErrorCollectorExtension"
    final val WEB_PROXY_ENABLED: String = "webProxyEnabled"
    final val WEB_PROXY_TYPE: String = "webProxyType"
    final val WEB_PROXY_ADDRESS: String = "webProxyAddress"
    final val API_PROXY_HOST: String = "apiProxyHost"
    final val API_PROXY_PORT: String = "apiProxyPort"
    final val API_CONTEXT: String = "apiContext"
    final val TEST_OBJECT: String = "testObject"
    final val OPEN_REPORT_IN_BROWSER: String = "openReportInBrowser"
    final val CAPTURE_SNAPSHOT: String = "captureSnapshot"
    final val DB_LOG_ENABLED: String = "dbLogEnabled"
    final val CAL_LOG_ENABLED: String = "calLogEnabled"
    final val EXCEPTION_LISTENER_ENABLED: String = "exceptionListenerEnabled"
    final val BEDASH_LISTENER_ENABLED: String = "beDashListenerEnabled"
    final val DP_TAGS_INCLUDE: String = "dpTagsInclude"
    final val DP_TAGS_EXCLUDE: String = "dpTagsExclude"
    final val SSH_COMMAND_WAIT: String = "sshCommandWait"
    final val SOFT_ASSERT_ENABLED: String = "softAssertEnabled"
    final val OUTPUT_DIRECTORY: String = "outputDirectory"
    final val EMAIL_RETENTION_POLICY: String = "emailRetentionPolicy"
    final val URL_CONVERT_CLASS: String = "urlConvertClass"
    final val WEB_DRIVER_LISTENER: String = "webDriverListener"
    final val VALIDATE_INTERNALS_END_POINT: String = "viEndPoint"
    final val TEST_METHOD_SIGNATURE: String = "testMethodSignature"
    final val TEST_METHOD_PC_MAP: String = "TestMethodPCMap"
    final val TEST_PC_MAP: String = "TestPCMap"
    final val PLUGIN_CONFIG_PATH: String = "pluginConfigPath"
    final val TEST_DATA_FILE: String = "testDataFile"

    final val LOCAL_MACHINE: String = "LocalMachine"
}
